<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHXWFEZA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHXWFEZA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHXWFEZA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHXWFEZA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHXWFEZA\App_KernelDevDebugContainer([
    'container.build_hash' => 'HXWFEZA',
    'container.build_id' => '2dee3963',
    'container.build_time' => 1700537877,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHXWFEZA');
